################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### Ã‰cole Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################


name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
# python
  - numpy
  - python=3.12
  - scipy
  - sympy

# jupyter
  - ipywidgets
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab
  - notebook


  # computing stuff on cpu only
  - pytorch-cpu  


  - pip
  - pip:
  # computing stuff
    - ngsolve
    - gmsh
    - tqdm
    - meshio
    - matplotlib
    - "pyvista[jupyter]"
  # mechanics stuff
    - neurom-py==3.1.21
