############################################################## Book settings ###

title: Welcome to [Jeanne, Cherrière, Daby-Seesaram, CSMA 2026]'s demos!
author: Octave Jeanne, Théodore Cherrière, Alexandre Daby-Seesaram
logo: logo.png
copyright: "2026"
only_build_toc_files: true

######################################################### Execution settings ###

execute:
  execute_notebooks: off
  # execute_notebooks: force

############################################################# Parse settings ###

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
  myst_dmath_double_inline: true # MG20230531: option is ignored, cf. https://github.com/executablebooks/jupyter-book/issues/1738

############################################################## HTML settings ###

html:
  use_repository_button: true
  use_issues_button: false

############################################################# LaTeX settings ###

latex:
  latex_engine: pdflatex  # pdflatex, xelatex (recommended for unicode), luatex, platex, uplatex
  use_jupyterbook_latex: true
  # latex_documents:
  #   targetname: "book.tex"

# bibtex_bibfiles:
#   - "references.bib"

############################################################# Launch settings ###

repository:
  url: https://github.com/AlexandreDabySeesaram/OJ_internship
  path_to_book: .
  branch: main

launch_buttons:
  notebook_interface: jupyterlab  # jupyterlab, classic
  binderhub_url: https://mybinder.org
  # colab_url: https://colab.research.google.com
  # jupyterhub_url: https://jupytercloud.idcs.polytechnique.fr/jupyter
